
import { Geist, Geist_Mono, Jost } from "next/font/google";
import { Roboto, Open_Sans, Lato, Poppins, Inter } from "next/font/google";

import "./globals.css";
import Footer from "./footer/Footer";
import Header from "./header/Header";



// Font configurations
export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-open-sans",
  display: "swap",
});

export const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-jost",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});



const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Spreadnext — Where Careers Meet Community",
  description: "Generated by create next app",
  icons: {
    icon: "/spreads.svg",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${roboto.variable} ${openSans.variable} ${lato.variable} ${poppins.variable} ${inter.variable}  antialiased`}
      >
        <div style={{ paddingTop: "35px" }}>
          <Header />
        </div>
        
        {children}

        <Footer />
      </body>
    </html>
  );
}